set spell
set ruler
set title
set number
set hlsearch
set linebreak
set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set nocompatible
set scrolloff=1
set background=dark
syntax enable
filetype plugin on
