unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

let mapleader=" "

set ttimeoutlen=50
set ruler
set title
set number
set hlsearch
set linebreak
set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set nocompatible
set scrolloff=1
set background=dark
if has('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif
syntax enable
filetype plugin indent on

autocmd FileType markdown,gitcommit,text setlocal spell

if has('termguicolors')
  set termguicolors
endif
silent! colorscheme catppuccin_mocha

inoremap jk <Esc>
