---
# Ansible Galaxy requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Required for homebrew, homebrew_cask, and osx_defaults modules
  - name: community.general
    version: ">=3.0.0"
