# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Suppress the warning message
# typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Theme
source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme

# Catppuccin theme configuration
#zstyle ':catppuccin:p10k' 'theme' 'rainbow'
#zstyle ':catppuccin:p10k' 'flavour' 'mocha'
#source ~/.config/zsh/plugins/catppuccin-powerlevel10k-themes/catppuccin-powerlevel10k-themes.plugin.zsh

# Environment Setup
export EDITOR=$(which nvim >/dev/null && echo "nvim" || echo "vim")
[[ $EDITOR == "nvim" ]] && alias vim="nvim"
[[ $(which codium) ]] && alias code="codium"

# Load Custom Aliases
source ~/.config/zsh/aliases

# Load Custom Host Configurations
[[ -f "$HOME/.config/zsh/hosts" ]] && source "$HOME/.config/zsh/hosts" && alias hosts="cat $HOME/.config/zsh/hosts"

# ZSH Plugins
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# Development Environment Managers
if command -v pyenv &> /dev/null; then
    export PYENV_ROOT="$HOME/.pyenv"
    [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi

if command -v nvm &> /dev/null; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"
fi

# OS Specific Configurations
if [[ $(uname) == "Linux" ]]; then
    path+=/home/pi/.local/bin
fi

if [[ $(uname) == "Darwin" ]]; then
    # Docker Desktop
    if [[ $(which docker) ]]; then
        # The following lines have been added by Docker Desktop to enable Docker CLI completions.
        fpath=(/Users/$USER/.docker/completions $fpath)
        autoload -Uz compinit
        compinit
        # End of Docker CLI completions
    fi

    # TODO: Fix zsh-autocomplete for Raspberry Pi
    source ~/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
fi

# TMUX Session Management
if command -v tmux &> /dev/null; then
    # Auto-start TMUX only in regular terminal
    # This function will be called after zsh initialization is complete
    _start_tmux_after_init() {
        # Only run this function once
        add-zsh-hook -d precmd _start_tmux_after_init
        
        # Only try to start tmux if we're not already in a tmux session
        if [[ -z "$TMUX" && -n "$PS1" && \
              ! "$TERM" = *screen* && \
              ! "$TERM" = *tmux* && \
              "$TERM_PROGRAM" != "vscode" && \
              "$TERM_PROGRAM" != "cursor" ]]; then
            # Start tmux without producing output
            tmux new-session -A -s sesh >/dev/null 2>&1 || true
        fi
    }
    
    # Register the function to run after zsh initialization
    autoload -Uz add-zsh-hook
    add-zsh-hook precmd _start_tmux_after_init
fi


# Added by Windsurf
export PATH="/Users/jesse/.codeium/windsurf/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
